### ISSUE TITLE
[버그] 개발 컨테이너 안에서 소스 제어 패널 문제

### ISSUE THREAD

**Issue by NarciSource** [Daily1Hour/PickMe#26]
### 🐞 버그 요약

개발 컨테이너 안에서 소스 제어 패널에 깃 적용이 안되는 것처럼 나오네요.

### 🐛 작업할 항목

- .git은 복사 확인
- vscode의 소스 제어 패널에 변경사항으로 모든 코드가 보임
- ??

### 📣 제안 사항

IntelliJ 에서도 확인 요망

### 📚 추가 정보

![vscode](https://github.com/user-attachments/assets/697b04f7-d0a6-46a8-8131-2ac6ba7c4901)

**Comment by NarciSource** [comment]
## 라인 엔딩의 차이 문제

- Windows: CRLF
- Unix/Linux: LF
- macOS: CR(과거) LF(현재)

차이로 동일한 파일이 다른 운영체제에서 편집되었을 때 엔딩이 다르다.
그래서 깃에서 변경사항으로 감지.

**Comment by NarciSource** [comment]
.gitattributes파일에
```
* text=auto
```
옵션을 주면 깃에서 라인 엔딩을 자동으로 인식한다.

**Comment by Awlstn** [comment]
넵! 추가 완료 했습니다
